# Pytorch basics for DL newbies
> Numpy + AutoGrad

- 원본 : [link](https://github.com/TEAMLAB-Lecture/deep-learning-101-for-busan/blob/main/ch1/torch_basics.ipynb)


## numpy to tensor

In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [5]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())


torch.Size([2, 5])
2
torch.Size([2, 5])


### Array to Tensor

##### Data to tensor

In [6]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

##### ndArray to Tensor

> 들여쓴 블록



In [7]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### numpy like operations

In [12]:
data = [[3, 5, 20],[10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [13]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [14]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [15]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [16]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [17]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [18]:
x_data.shape

torch.Size([3, 3])

In [19]:
x_data.dtype

torch.int64

In [20]:
x_data.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

### Tensor handling

In [29]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.9972, 0.3039],
         [0.8690, 0.8243],
         [0.5010, 0.1183]],

        [[0.6530, 0.7373],
         [0.2573, 0.4854],
         [0.1416, 0.2750]]])

In [30]:
tensor_ex.view([-1, 6])

tensor([[0.9972, 0.3039, 0.8690, 0.8243, 0.5010, 0.1183],
        [0.6530, 0.7373, 0.2573, 0.4854, 0.1416, 0.2750]])

In [31]:
tensor_ex.reshape([-1,6])

tensor([[0.9972, 0.3039, 0.8690, 0.8243, 0.5010, 0.1183],
        [0.6530, 0.7373, 0.2573, 0.4854, 0.1416, 0.2750]])

In [32]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [34]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [36]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [37]:
b

tensor([0., 0., 0., 0., 0., 0.])

- `squeeze()` : size가 1인 차원 줄이기

In [50]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()

tensor([[0.3887, 0.5740],
        [0.2177, 0.4566]])

- `unsqueeze()` : n번째 차원 1로 채워서 차원 늘리기

In [52]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [53]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [56]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

## tensor operations

In [57]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [58]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [59]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [60]:
t1 + t2

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 1

In [61]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [62]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

- `mm()`, `dot()`, `matmul()`은 조금씩 다름, `mm()`을 가장 많이 사용함

In [63]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [64]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [65]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [66]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(4.0544)

In [67]:
a

tensor([0.9188, 0.9158, 0.3516, 0.5133, 0.8561, 0.7710, 0.2713, 0.8077, 0.8243,
        0.2533])

In [68]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: self must be a matrix

In [69]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [70]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

- `dot()`: 벡터간 계산 가능

In [72]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(1.0552)

- `mm()` : 매트릭스간 계산만 가능

In [73]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: self must be a matrix

In [74]:
a = torch.rand(5,2, 3)
b = torch.rand(5)
a.mm(b)

RuntimeError: self must be a matrix

- `matmul()` : 매트릭스와 벡터간 계산 가능 (브로드캐스팅이 일어남)

In [75]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.7742, 1.3969],
        [1.4558, 1.3227],
        [1.0233, 1.2330],
        [1.3569, 0.9567],
        [1.4290, 0.8015]])

In [82]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()

tensor([0.7742, 1.3969])

In [86]:
a[1].mm(torch.unsqueeze(b,1))

tensor([[1.4558],
        [1.3227]])

In [87]:
a[2].mm(torch.unsqueeze(b,1))


tensor([[1.0233],
        [1.2330]])

In [88]:
a[3].mm(torch.unsqueeze(b,1))


tensor([[1.3569],
        [0.9567]])

In [89]:
a[4].mm(torch.unsqueeze(b,1))


tensor([[1.4290],
        [0.8015]])

## tensor operations for ML/DL formula

- `softmax()` : 합이 1이 되도록 정규화해줌

In [91]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0) 
h_tensor


tensor([0.3458, 0.4224, 0.2318])

In [95]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)

y_label

tensor([1, 2, 2, 1, 1, 1, 1, 0, 3, 0])

In [96]:
y

tensor([[0, 3, 1, 2, 3],
        [2, 0, 4, 4, 0],
        [1, 0, 4, 0, 2],
        [2, 3, 3, 2, 3],
        [1, 4, 0, 2, 1],
        [0, 3, 2, 0, 1],
        [0, 4, 1, 3, 4],
        [4, 4, 1, 3, 3],
        [2, 1, 2, 3, 0],
        [4, 3, 1, 4, 2]])

In [97]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0]])

In [99]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [100]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## torch autogard

$$
y = w^2 \\ 
z = 10*y + 25 \\
z = 10*w^2 + 25 
$$

In [ ]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 50
z.backward()
w.grad

In [ ]:
w.grad

$$ Q = 3a^3 - b^2  $$

In [101]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad

tensor([36., 81.])

In [102]:
b.grad

tensor([-12.,  -8.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$

In [103]:
a.grad

tensor([36., 81.])

In [104]:
b.grad

tensor([-12.,  -8.])