# Lab Assignment - Numpy in a nutshell

Copyright 2018 © document created by [teamLab.gachon@gmail.com](teamLab.gachon@gmail.com)

URL : [GitHub/Teamlab](https://github.com/TeamLab/machine_learning_from_scratch_with_python/tree/master/lab_asssigment/1_lab_numpy)

In [1]:
import numpy as np

* **Q1 : n_size_ndarray_creation** 

In [28]:
def n_size_ndarray_creation(n, dtype=int):
    X = np.arange(n**2).reshape(n,n).astype(dtype)
    return X

In [29]:
n_size_ndarray_creation(5, dtype=float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

* **Q2 : zero_or_one_or_empty_ndarray** 

In [36]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=int):
    if type == 0:
        X = np.zeros(list(shape)).astype(dtype)
    elif type == 1:
        X = np.ones(list(shape)).astype(dtype)
    elif type == 99:
        X = np.empty(list(shape)).astype(dtype)
    
    return X

In [42]:
print(zero_or_one_or_empty_ndarray((3,4), type=0, dtype=float))
print(zero_or_one_or_empty_ndarray((2,5), type=1, dtype=int))
print(zero_or_one_or_empty_ndarray((3,3), type=99, dtype=str))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[['0.0' '0.0' '0.0']
 ['0.0' '0.0' '9.01e-321']
 ['8.456034395232316e-307' '4.450460074794833e-307' '2.376670579584e-312']]


* **Q3 : change_shape_of_ndarray** 

In [52]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        result = X.flatten()
    else:
        result = X.reshape(n_row,-1)

    return result

In [55]:
X = np.ones((4,4), dtype = int)
change_shape_of_ndarray(X, 1), change_shape_of_ndarray(X, 4)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

* **Q4 : concat_ndarray** 

In [115]:
def concat_ndarray(X_1, X_2, axis):
    try:
        # X_1, X_2의 입력값은 matrix or vector라는 가정
        if X_1.ndim > X_2.ndim:
            X_2 = X_2 = X_2.reshape(-1, X_2.size)
        elif X_2.ndim > X_1.ndim:
            X_1 = X_1= X_1.reshape(-1, X_1.size)
            
        result = np.concatenate([X_1,X_2],axis=axis)
        return result
    except:
        return False

In [125]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

print(concat_ndarray(a,b,0))
print(concat_ndarray(a,b,1))

c = np.array([1, 2])
d = np.array([5, 6, 7])

print(concat_ndarray(c, d, 0))
print(concat_ndarray(c, d, 1))

[[1 2]
 [3 4]
 [5 6]]
False
[1 2 5 6 7]
False


* **Q5 : normalize_ndarray** 

In [167]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 99 or X.ndim == 1:
        X = (X - np.mean(X))/np.std(X)
    elif axis == 0:
        X = (X - np.mean(X, axis = 0))/np.std(X, axis = 0)
    elif axis == 1:
        X = (X - np.mean(X, axis = 1).reshape(-1,1))/np.std(X, axis = 1).reshape(-1,1)

    return X


In [172]:
a = np.arange(12, dtype=np.float32)
print(normalize_ndarray(a))

b = np.arange(12, dtype = np.float32).reshape(6,2)
print(normalize_ndarray(b))
print(normalize_ndarray(b,1))
print(normalize_ndarray(b,0))

[-1.593255   -1.3035723  -1.0138896  -0.7242068  -0.4345241  -0.14484136
  0.14484136  0.4345241   0.7242068   1.0138896   1.3035723   1.593255  ]
[[-1.593255   -1.3035723 ]
 [-1.0138896  -0.7242068 ]
 [-0.4345241  -0.14484136]
 [ 0.14484136  0.4345241 ]
 [ 0.7242068   1.0138896 ]
 [ 1.3035723   1.593255  ]]
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]]
[[-1.46385 -1.46385]
 [-0.87831 -0.87831]
 [-0.29277 -0.29277]
 [ 0.29277  0.29277]
 [ 0.87831  0.87831]
 [ 1.46385  1.46385]]


* **Q6 : save_ndarray** 

In [181]:
def save_ndarray(X, filename="test.npy"):
    f = open("./" + filename, 'w')
    f.write(str(X))
    f.close()

In [183]:
X = np.arange(32, dtype = np.float32).reshape(4,-1)
save_ndarray(X, 'test.npy')

* **Q7 : boolean_index** 

In [184]:
def boolean_index(X, condition):
    result = np.where(eval(str("X") + condition))
    return result

In [190]:
a = np.arange(32, dtype=np.float32).reshape(4,-1)
print(boolean_index(a, '== 3'))

b = np.arange(32, dtype = np.float32)
print(boolean_index(b, "> 6"))

(array([0], dtype=int64), array([3], dtype=int64))
(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)


* **Q8 : find_nearest_value** 

In [223]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X - target_value))]

In [224]:
X = np.random.uniform(0,1,100)
target_value = 0.3
find_nearest_value(X, target_value)

0.3072654992971422

* **Q9 : get_n_largest_values** 

In [232]:
def get_n_largest_values(X, n):
    result = X[X.argsort()[::-1][:n]]
    return result

In [233]:
X = np.random.uniform(0,1,100)
get_n_largest_values(X, 3)

array([0.99432464, 0.9818719 , 0.97703266])