In [2]:
import numpy as np

## all & any

* Array의 데이터 전부(and) 또는 일부 (or)가 조건에 만족 여부 반환

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a < 4 # a의 모든 값이 4보다 작은지 묻는 것 

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [7]:
np.all(a < 10)

True

In [9]:
np.all(a < 5)

False

In [12]:
np.any(a > 5)

True

In [14]:
np.any(a < 0)

False

## Comparison operation #1

* numpy는 배열의 크기가 동일할 때 element간 비교의 결과를 boolean type으로 반환(element-wise operation)

In [15]:
test_a = np.array([1,3,0])
test_b = np.array([5,2,1])

In [16]:
test_a == test_b

array([False, False, False])

In [17]:
(test_a > test_b).any() # 하나라도 True면 True 반환

True

## Comparision operation #2

* logical_and, not, or

In [18]:
a = np.array([1,3,0])
np.logical_and(a > 0, a < 3) # and 조건

array([ True, False, False])

In [19]:
b = np.array([True, False, True], bool)
np.logical_not(b) # not 조건

array([False,  True, False])

In [21]:
c = np.array([False, False, False], bool)
np.logical_or(b, c) # or 조건

array([ True, False,  True])

## np.where

* 조건을 만족하는 index값을 반환

In [22]:
a

array([1, 3, 0])

In [24]:
np.where(a > 2)
# 1,3,0 중 2보다 큰 값인 3의 index값(1번째 위치)을 array가 담긴 tuple로 반환

(array([1], dtype=int64),)

In [25]:
np.where(a < 3)[0]

array([0, 2], dtype=int64)

In [27]:
np.where(a < 3, 3, 2)
# 조건을 만족하면 3을, 만족하지 않으면 2를 반환

array([3, 2, 3])

In [28]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [29]:
np.isfinite(a) # 유한한 숫자인지

array([ True, False, False])

In [31]:
np.isinf(a) # Inf 값인지

array([False, False,  True])

## argmax & argmin

* array내 최댓값 또는 최솟값의 index를 반환함

In [33]:
a = np.array([1,2,3,4,5,6,78,23,3])
np.argmax(a), np.argmin(a)

(6, 0)

* axis 기반의 반환

In [35]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)


(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

* argsort() : 작은 것부터 순서대로 index를 반환

In [37]:
a = np.array([1,2,3,4,5,6,78,34,3])
a.argsort()

array([0, 1, 2, 8, 3, 4, 5, 7, 6], dtype=int64)

In [38]:
a.argsort()[::-1] # 반대로 정렬

array([6, 7, 5, 4, 3, 8, 2, 1, 0], dtype=int64)

## Boolean index

* 특정 조건에 따른 값을 배열 형태로 추출
* Comparision operation 함수들도 모두 사용 가능

In [39]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

* 원래 array와 boolean array가 shape이 같아야 함 

In [41]:
test_array.shape, (test_array > 3).shape

((8,), (8,))

In [43]:
condition = test_array > 3
test_array[condition]

array([4., 8., 9., 7.])

## Fancy index

* numpy는 array를 index value로 사용해서 값 추출

In [45]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int) # 반드시 integer로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

* integer array의 index값들은 원래 array의 len을 넘어서는 안됨

In [46]:
a.take(b) # take()함수 : bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [48]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0],int)
c = np.array([0,1,1,1,1],int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [50]:
a[b] # b = [0,0,1,1,0] 이니까 row만 반환함

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])