# Lab Assignment - Build a matrix

Copyright 2018 © document created by teamLab.gachon@gmail.com

URL : [GitHub/Teamlab](https://github.com/TeamLab/machine_learning_from_scratch_with_python/tree/master/lab_asssigment/2_lab_build_matrix)

* **Q1 : get_rating_matrix** 

In [31]:
import numpy as np
import pandas as pd


def get_rating_matrix(filename, dtype=np.float32):
    movie_rating = pd.read_csv(filename)

    rating_pivot_table = movie_rating.pivot_table(
        values = ['rating'],
        index = movie_rating.source,
        columns = movie_rating.target,
        fill_value = 0
        )
    matrix = np.array(rating_pivot_table)
    
    return matrix

In [32]:
print(get_rating_matrix('./movie_rating.csv'))

[[3.  0.  3.5 0.  4.5 0. ]
 [0.  3.  3.5 0.  3.  3.5]
 [0.  3.  4.  5.  3.  3.5]
 [3.  2.5 3.5 3.5 3.  2.5]
 [2.  3.  4.  3.  3.  0. ]
 [0.  0.  4.5 4.  0.  0. ]]


* **Q2 : get_frequent_matrix** 

In [49]:
def get_frequent_matrix(filename, dtype=np.float32):
    purchase = pd.read_csv(filename)
    df_purchase = purchase.groupby(['source','target'])['target'].count().unstack()
    matrix = np.array(df_purchase)
    
    return matrix

In [50]:
print(get_frequent_matrix('./1000i.csv'))

[[19 17 14 11 17 25  7 22  5 18 10 13 13  8 20 10  9 10 16 15  9 11 17 15
  14  8  6 12 18 12  6 18  9 24  7 19 14  6  4 12 15 14 20  9 12 16 11  9
  11 12]
 [20 16 10 15 17 18 10 13  5 19  8 14 14  9 15 14 13  8 12  9  5 10 28 18
   7  8  6 19 14 13 11 12 18 15  7 11 17  9  5  5 13 12 15  9 13 16 16 10
  16  9]
 [12 16 13 19 23 19  5 14  5 18  7  6 14  8 20 17 14 11 16 12  7  9 23 12
  12  8  7 23 26 10  9 20 16 11  4 19 12 12  5 10 10 14 10 17 15 16 11 17
   9 11]
 [14 14 19 11 11 18  7 16  7 17  6 19 18 12 13 13 14  9 21 16  6  6 19 14
  19  5 12 14 18 11 11 21 15 10 11 14 17 21  6 14  9 16 18 12 16 16 26 16
  12 20]
 [13  7  8 15 13 16  3 19 11 12  7 10 13 14 16 14 23  9 13 10 11  3 11 14
   9  6 11 16 18 11  5 14 10 16 10  5 14 11  3  9 11 10 16  8 13 20 14 18
  21  3]]
